import { Material } from "@/types/type";

export function buildChapters(progress: Record<string, boolean>) {
  return Materials.reduce((acc, m) => {
    const found = acc.find((c) => c.id === m.chapter);
    const isRead = !!progress[m.slug]; // ← Supabaseから渡される進捗で判定

    if (found) {
      found.materialsCount++;
      if (isRead) found.completedCount++;
    } else {
      acc.push({
        id: m.chapter,
        title: m.chapterTitle,
        materialsCount: 1,
        completedCount: isRead ? 1 : 0,
      });
    }
    return acc;
  }, [] as { id: string; title: string; materialsCount: number; completedCount: number }[]);
}

export const Materials: Omit<Material, "isRead">[] = [
  // Chapter: Setup (環境構築)
  {
    slug: "setup/start",
    title: "はじめに",
    chapter: "setup",
    chapterTitle: "環境構築",
    readingTime: 10,
  },
  {
    slug: "setup/nodejs-npm",
    title: "Node.jsとnpmのインストール",
    chapter: "setup",
    chapterTitle: "環境構築",
    readingTime: 15,
  },
  {
    slug: "setup/vscode",
    title: "VSCodeの初期設定",
    chapter: "setup",
    chapterTitle: "環境構築",
    readingTime: 15,
  },
  {
    slug: "setup/terminal",
    title: "ターミナルの使い方",
    chapter: "setup",
    chapterTitle: "環境構築",
    readingTime: 10,
  },
  {
    slug: "setup/git-github",
    title: "GitとGitHubの初期設定",
    chapter: "setup",
    chapterTitle: "環境構築",
    readingTime: 20,
  },
  {
    slug: "setup/vite-project",
    title: "Viteでプロジェクトを作成する",
    chapter: "setup",
    chapterTitle: "環境構築",
    readingTime: 10,
  },
  {
    slug: "setup/folder-structure",
    title: "プロジェクトのフォルダ構造を理解する",
    chapter: "setup",
    chapterTitle: "環境構築",
    readingTime: 10,
  },
  {
    slug: "setup/common-errors",
    title: "よくあるエラーと解決策",
    chapter: "setup",
    chapterTitle: "環境構築",
    readingTime: 10,
  },
  {
    slug: "setup/summary",
    title: "まとめとチェックリスト",
    chapter: "setup",
    chapterTitle: "環境構築",
    readingTime: 10,
  },

  // Chapter: HTML/CSS
  {
    slug: "html-css/start",
    title: "はじめに",
    chapter: "html-css",
    chapterTitle: "HTML/CSS",
    readingTime: 10,
  },
  {
    slug: "html-css/html-basics",
    title: "HTMLの基礎",
    chapter: "html-css",
    chapterTitle: "HTML/CSS",
    readingTime: 15,
  },
  {
    slug: "html-css/css-basics",
    title: "CSSの基礎",
    chapter: "html-css",
    chapterTitle: "HTML/CSS",
    readingTime: 15,
  },
  {
    slug: "html-css/box-model",
    title: "BoxModelを理解する",
    chapter: "html-css",
    chapterTitle: "HTML/CSS",
    readingTime: 15,
  },
  {
    slug: "html-css/flexbox",
    title: "Flexboxでレイアウトを作る",
    chapter: "html-css",
    chapterTitle: "HTML/CSS",
    readingTime: 15,
  },
  {
    slug: "html-css/grid",
    title: "Gridでレイアウトを作る",
    chapter: "html-css",
    chapterTitle: "HTML/CSS",
    readingTime: 15,
  },
  {
    slug: "html-css/responsive",
    title: "レスポンシブデザインの基礎",
    chapter: "html-css",
    chapterTitle: "HTML/CSS",
    readingTime: 15,
  },
  {
    slug: "html-css/css-techniques",
    title: "よく使うCSSテクニック",
    chapter: "html-css",
    chapterTitle: "HTML/CSS",
    readingTime: 15,
  },
  {
    slug: "html-css/portfolio",
    title: "ポートフォリオサイトを作ろう",
    chapter: "html-css",
    chapterTitle: "HTML/CSS",
    readingTime: 20,
  },
  {
    slug: "html-css/tailwindcss",
    title: "TailwindCSS入門",
    chapter: "html-css",
    chapterTitle: "HTML/CSS",
    readingTime: 15,
  },
  {
    slug: "html-css/summary",
    title: "まとめと次のステップ",
    chapter: "html-css",
    chapterTitle: "HTML/CSS",
    readingTime: 10,
  },

  // Chapter: JavaScript
  {
    slug: "javascript/start",
    title: "はじめに",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 10,
  },
  {
    slug: "javascript/basics",
    title: "JavaScriptの基礎",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 20,
  },
  {
    slug: "javascript/operators-conditions",
    title: "演算子と条件分岐",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 15,
  },
  {
    slug: "javascript/functions",
    title: "関数",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 15,
  },
  {
    slug: "javascript/array-basics",
    title: "配列の基礎",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 20,
  },
  {
    slug: "javascript/array-methods",
    title: "配列の高階関数",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 20,
  },
  {
    slug: "javascript/object-basics",
    title: "オブジェクトの基礎",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 20,
  },
  {
    slug: "javascript/array-of-objects",
    title: "オブジェクトの配列を扱う",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 20,
  },
  {
    slug: "javascript/async-basics",
    title: "非同期処理の基礎",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 20,
  },
  {
    slug: "javascript/fetch-api",
    title: "fetchでAPI通信",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 20,
  },
  {
    slug: "javascript/import-export",
    title: "importとexport",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 15,
  },
  {
    slug: "javascript/fizzbuzz",
    title: "FizzBuzzを作ろう",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 15,
  },
  {
    slug: "javascript/quiz-app",
    title: "クイズアプリを作ろう",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 30,
  },
  {
    slug: "javascript/vending-machine",
    title: "自動販売機を作ろう",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 20,
  },
  {
    slug: "javascript/memo-app",
    title: "メモアプリを作ろう",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 20,
  },
  {
    slug: "javascript/dom-basics",
    title: "DOM操作の基礎",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 20,
  },
  {
    slug: "javascript/localstorage",
    title: "localStorageで保存する",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 15,
  },
  {
    slug: "javascript/pokedex",
    title: "ポケモン図鑑を作ろう",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 20,
  },
  {
    slug: "javascript/summary",
    title: "まとめと次のステップ",
    chapter: "javascript",
    chapterTitle: "JavaScript",
    readingTime: 10,
  },

  // Chapter: React Basics (React基礎)
  {
    slug: "react-basics/start",
    title: "はじめに",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 10,
  },
  {
    slug: "react-basics/concepts",
    title: "Reactの基本概念",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/jsx",
    title: "JSXの基礎",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/components",
    title: "コンポーネントを作る",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/props",
    title: "Propsでデータを渡す",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/state",
    title: "Stateで状態を管理する",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/events",
    title: "イベントハンドリング",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/lists",
    title: "リスト描画",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/conditional-rendering",
    title: "条件分岐での描画",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/forms",
    title: "フォームの基礎",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/useeffect",
    title: "useEffectの基礎",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/fetching-data",
    title: "APIからデータを取得する",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 20,
  },
  {
    slug: "react-basics/lifting-state",
    title: "Stateのリフトアップ",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/js-vs-react",
    title: "JSとReactの違いを理解しよう",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/counter-app",
    title: "カウンターアプリを作ろう",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/quiz-app",
    title: "クイズアプリを作ろう",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 20,
  },
  {
    slug: "react-basics/todo-app",
    title: "タスク管理アプリを作ろう",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 20,
  },
  {
    slug: "react-basics/custom-hooks",
    title: "カスタムフック入門",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/context-api",
    title: "ContextAPI入門",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 15,
  },
  {
    slug: "react-basics/pokedex-app",
    title: "Pokedexアプリを作ろう",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 20,
  },
  {
    slug: "react-basics/summary",
    title: "まとめと次のステップ",
    chapter: "react-basics",
    chapterTitle: "React基礎",
    readingTime: 10,
  },

  // Chapter: React Advanced (React応用)
  {
    slug: "react-advanced/start",
    title: "はじめに",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 10,
  },
  {
    slug: "react-advanced/controlled-components",
    title: "ControlledComponents完全理解",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 25,
  },
  {
    slug: "react-advanced/form-validation",
    title: "フォームバリデーション",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 25,
  },
  {
    slug: "react-advanced/react-hook-form",
    title: "ReactHookForm",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 20,
  },
  {
    slug: "react-advanced/state-design",
    title: "State管理の設計",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 20,
  },
  {
    slug: "react-advanced/crud-basics",
    title: "CRUDの基礎",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 20,
  },
  {
    slug: "react-advanced/crud-patterns",
    title: "CRUDアプリの実装パターン",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 15,
  },
  {
    slug: "react-advanced/modal",
    title: "モーダルの実装",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 20,
  },
  {
    slug: "react-advanced/tailwind-mastery",
    title: "TailwindCSSを使いこなす",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 20,
  },
  {
    slug: "react-advanced/shadcn-ui",
    title: "shadcnui入門",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 15,
  },
  {
    slug: "react-advanced/react-router",
    title: "ReactRouter入門",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 20,
  },
  {
    slug: "react-advanced/ui-logic-separation",
    title: "UIとロジックの分離",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 20,
  },
  {
    slug: "react-advanced/performance",
    title: "パフォーマンス最適化入門",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 15,
  },
  {
    slug: "react-advanced/error-loading",
    title: "エラーハンドリングとローディング",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 20,
  },
  {
    slug: "react-advanced/todo-full",
    title: "タスク管理アプリ本格版",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 30,
  },
  {
    slug: "react-advanced/book-review",
    title: "ブックレビューアプリを作ろう",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 30,
  },
  {
    slug: "react-advanced/summary",
    title: "まとめと次のステップ",
    chapter: "react-advanced",
    chapterTitle: "React応用",
    readingTime: 10,
  },

  // Chapter: Firebase
  {
    slug: "firebase/start",
    title: "はじめに",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 10,
  },
  {
    slug: "firebase/create-project",
    title: "Firebaseプロジェクトの作成",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/setup",
    title: "Firebaseの初期設定",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/firestore-basics",
    title: "Firestoreの基礎",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/firestore-read",
    title: "Firestoreでデータを取得する",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/firestore-create",
    title: "Firestoreでデータを追加する",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/firestore-update",
    title: "Firestoreでデータを更新する",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/firestore-delete",
    title: "Firestoreでデータを削除する",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 10,
  },
  {
    slug: "firebase/firestore-query",
    title: "Firestoreのクエリ",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/auth-basics",
    title: "FirebaseAuthenticationの基礎",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 10,
  },
  {
    slug: "firebase/auth-signup",
    title: "ユーザー登録機能の実装",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/auth-login-logout",
    title: "ログインログアウトの実装",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/auth-state",
    title: "認証状態の管理",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/auth-guard",
    title: "認証ガード",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/user-profile",
    title: "ユーザー情報の管理",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/storage-basics",
    title: "FirebaseStorageの基礎",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/image-upload",
    title: "画像アップロード機能の実装",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/user-data",
    title: "ユーザーごとのデータ管理",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/security-rules",
    title: "セキュリティルール入門",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/hosting",
    title: "FirebaseHostingでデプロイ",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 10,
  },
  {
    slug: "firebase/functions",
    title: "FirebaseFunctions入門",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/swr",
    title: "SWRとFirestore",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 15,
  },
  {
    slug: "firebase/todo-integration",
    title: "TodoアプリにFirebaseを統合",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 25,
  },
  {
    slug: "firebase/summary",
    title: "まとめと次のステップ",
    chapter: "firebase",
    chapterTitle: "Firebase",
    readingTime: 10,
  },

  // Chapter: Git
  {
    slug: "git/start",
    title: "はじめに",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 15,
  },
  {
    slug: "git/concepts",
    title: "Gitの基本概念",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 25,
  },
  {
    slug: "git/basic-commands",
    title: "Gitの基本操作",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 20,
  },
  {
    slug: "git/github-repo",
    title: "GitHubリポジトリの作成",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 20,
  },
  {
    slug: "git/remote",
    title: "ローカルとリモートの連携",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 25,
  },
  {
    slug: "git/branching",
    title: "ブランチを使った開発",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 20,
  },
  {
    slug: "git/merge",
    title: "マージの基礎",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 20,
  },
  {
    slug: "git/pull-request",
    title: "PullRequestの基礎",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 20,
  },
  {
    slug: "git/code-review",
    title: "コードレビューの基礎",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 25,
  },
  {
    slug: "git/conflict-resolution",
    title: "コンフリクトの理解と解決",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 25,
  },
  {
    slug: "git/conflict-prevention",
    title: "コンフリクトを避けるための設計",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 20,
  },
  {
    slug: "git/gitignore",
    title: "gitignoreの使い方",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 20,
  },
  {
    slug: "git/useful-commands",
    title: "Gitのよく使うコマンド",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 20,
  },
  {
    slug: "git/github-features",
    title: "GitHubの便利機能",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 15,
  },
  {
    slug: "git/issues",
    title: "Issue管理",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 25,
  },
  {
    slug: "git/github-projects",
    title: "GitHubProjectsでタスク管理",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 20,
  },
  {
    slug: "git/team-workflow",
    title: "チーム開発のワークフロー",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 20,
  },
  {
    slug: "git/team-tips",
    title: "チーム開発での注意点",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 20,
  },
  {
    slug: "git/team-practice",
    title: "チーム開発を体験しよう",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 25,
  },
  {
    slug: "git/summary",
    title: "まとめと次のステップ",
    chapter: "git",
    chapterTitle: "Git",
    readingTime: 20,
  },

  // Chapter: Next.js
  {
    slug: "nextjs/start",
    title: "はじめに",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 15,
  },
  {
    slug: "nextjs/concepts",
    title: "Nextjsの基本概念",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/create-project",
    title: "Nextjsプロジェクトの作成",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/app-router",
    title: "AppRouterの基礎",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/file-routing",
    title: "ファイルベースルーティング",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/link",
    title: "Linkコンポーネント",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/layouts",
    title: "レイアウトの使い方",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/server-client",
    title: "ServerとClientComponents",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/server-fetching",
    title: "ServerComponentでデータフェッチ",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/loading-error",
    title: "loadingとerror",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/metadata",
    title: "メタデータの設定",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/image",
    title: "Imageコンポーネント",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/api-routes",
    title: "APIRoutes",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/env-variables",
    title: "環境変数の使い方",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/tailwind-setup",
    title: "TailwindCSSの設定",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/deploy",
    title: "ビルドとデプロイ",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/isr-ssg",
    title: "ISRとSSG",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/blog-app",
    title: "ブログアプリを作ろう",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 15,
  },
  {
    slug: "nextjs/firebase",
    title: "NextjsとFirebase",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },
  {
    slug: "nextjs/summary",
    title: "まとめと次のステップ",
    chapter: "nextjs",
    chapterTitle: "Next.js",
    readingTime: 10,
  },

  // Chapter: Development (開発プロセス)
  {
    slug: "development/start",
    title: "はじめに",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/overview",
    title: "開発フローの全体像",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/ideation",
    title: "企画アイデアの出し方",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/requirements-basics",
    title: "要件定義の基礎",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/requirements-doc",
    title: "要件定義書を書こう",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/screen-design-basics",
    title: "画面設計の基礎",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/screen-flow",
    title: "画面遷移図を作る",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/screen-elements",
    title: "画面ごとの要素を洗い出す",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/data-design-basics",
    title: "データ設計の基礎",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/firestore-design",
    title: "Firestoreのデータ構造を設計する",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/data-design-example",
    title: "データ設計の実例",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/api-design",
    title: "API設計",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/task-breakdown",
    title: "タスク分割の基礎",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/issue-management",
    title: "Issueでタスク管理",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/task-example",
    title: "タスク分割の実例",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/component-design",
    title: "コンポーネント分割の設計",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/coding-rules",
    title: "チームでのコーディングルール",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/workflow",
    title: "開発の進め方",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/testing",
    title: "テストの基礎",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/release-checklist",
    title: "リリース前チェックリスト",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/mvp-workshop",
    title: "MVP開発ワークショップ",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },
  {
    slug: "development/summary",
    title: "まとめとMVP開発へ",
    chapter: "development",
    chapterTitle: "開発プロセス",
    readingTime: 10,
  },

  // Chapter: Advanced (上級編)
  {
    slug: "advanced/start",
    title: "はじめに",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/typescript-basics",
    title: "TypeScriptの基礎",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/typescript-syntax",
    title: "TypeScriptの基本構文",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/interface-type",
    title: "interfaceとtype",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/generics",
    title: "ジェネリクス入門",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/typescript-react",
    title: "TypeScriptとReact",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/typescript-firebase",
    title: "TypeScriptとFirebase",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/typescript-best-practices",
    title: "TypeScriptのベストプラクティス",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/shadcn-guide",
    title: "shadcnui完全ガイド",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/shadcn-rhf",
    title: "shadcnuiとReactHookForm",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/swr-basics",
    title: "SWRの基礎",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/swr-firestore",
    title: "SWRとFirestore",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/react-query",
    title: "ReactQuery入門",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/zustand",
    title: "Zustandで状態管理",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/vitest",
    title: "Vitestでテスト",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/docker-basics",
    title: "Dockerの基礎",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/docker-dev",
    title: "Dockerで開発環境を作る",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/performance",
    title: "パフォーマンス最適化",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/accessibility",
    title: "アクセシビリティ",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/pwa",
    title: "PWA",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/cicd",
    title: "CICD入門",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
  {
    slug: "advanced/summary",
    title: "まとめと今後の学習",
    chapter: "advanced",
    chapterTitle: "上級編",
    readingTime: 10,
  },
];
